### ISSUE TITLE
Cannot find a way to generate default routing in 'Choice'

### ISSUE THREAD

**Issue by JiangKeshu** [sakazuki/step-functions-draw.io#13]
I have a use case of setting Default routing in Choice as following:
```javascript
"CheckEnd": {
  "Type": "Choice",
  "Choices": [
    {
        "Variable": "$.Actions.IsEnd",
        "BooleanEquals": true,
        "Next": "End"
    }],
    "Default": "GetStackStatus"
},
```
I tried to give 'Default' in conditions but generated JSON looks like below:
```javascript
    "CheckEnd": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.Actions.IsEnd",
          "BooleanEquals": true,
          "Next": "End"
        },
        {
          "Next": "CheckFor_NewExecution"
        }
      ]
    },
```
Do you think it is possible to support default routing?

**Comment by sakazuki** [comment]
Hi @JiangKeshu ,

![stepfunction-draw io-issue](https://user-images.githubusercontent.com/1878694/50280975-6737f400-0491-11e9-96b5-a4e01bd1b857.png)

This diagram outputs the following
```
{
  "StartAt": "Choice",
  "States": {
    "Choice": {
      "Type": "Choice",
      "Choices": [
        {
          "Variable": "$.Actions.IsEnd",
          "BooleanEquals": true,
          "Next": "End"
        }
      ],
      "Default": "GetStackStatus"
    },
    "GetStackStatus": {
      "Type": "Task",
      "TimeoutSeconds": 60,
      "End": true
    }
  }
}
```
You can select the choice state and drag from the "D"efault circle to the next state.
If this cannot solve your problem, Please let me know the procedure to the your situation.

**Comment by sakazuki** [comment]
closed this issue, because there is not update for long time.
