### ISSUE TITLE
Add a option to import existing json.

### ISSUE THREAD

**Issue by oxydron** [sakazuki/step-functions-draw.io#14]
The same way it now have an option to export, would be nicer to have an import option.

**Comment by fadams** [comment]
+1 from me, it'd definitely be nice to be able to import existing step functions, the ability to round-trip is pretty close to essential for serious use.

**Comment by DALDEI** [comment]
+11 for my use cases, being able to import is *more important* then either interactive composition or exporting.   Stepfunctions are code.  As code, they are managed in a build system in source control.  Versioning, bug fixes, development, deployment, testing -- all need to work at the 'text file code' level first, diagraming second.   The code needs to be 100% transparent and understandable, the diagraming is 'nice to have' (VERY nice to have) but servers a second order purpose to the actual state machine/step function definition source.    As annoying as it is, this is likely why AWS console is 1 way only -- the diagram is not intended to be the ultimate source of truth.  
I would love to embed a visualization of the state machine (particularly a running one, like the console does) in our internal monitoring systems, as well as publish the diagram in the documentation.   But if the only way to get the diagram is to manually create the step function in draw.io -- that doesnt make it past the first 5 minutes -- (when you run the step function and it doesnt quite work so you have to 'tweak' it -- having to go to the 'live' diagram and find the place in the diagram and fix it there then export then import into AWS and repeat -- did not survive reality very long)   -- However being able to point a (embeded) draw.io diagram at either checked in source or extracted-from-api describe-state-machine-from-execution - that has legs a mile long.

**Comment by sakazuki** [comment]
I released the beta 

https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.4.0-beta1/aws-step-functions.js

**New feature**
- Import JSON

**Known issue**
- It fails to layout parallel states.

If you have interested in it, please try it.

**Comment by sakazuki** [comment]
I released v0.4.0-beta2
You can test it with the url
https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.4.0-beta2/aws-step-functions.js

**Comment by sakazuki** [comment]
I released v0.4.0

**Comment by fadams** [comment]
@sakazuki so sorry for not replying sooner, I've been rather distracted.
Many thanks for implementing this feature, it's great and much appreciated.
ありがとうございました
