### ISSUE TITLE
cell.getAttribute error after every change

### ISSUE THREAD

**Issue by drfish** [sakazuki/step-functions-draw.io#15]
After every change once the plugin is loaded and page refreshed I get the following message:

Error (cell.getAttribute is not a function)
This file has been modified. Do you want to synchronize these changes?

I click synchronize each time and appear to be able to keep working but it's every tiny little change. Any ideas?

Problems aside, I love that this exists, I've been learning step functions and was telling one of the other people at the company that if someone just wired this to a flow chart maker it'd be the easiest tool ever to create for.

**Comment by drfish** [comment]
Oh, and just in case anyone else is struggling to duplicate:
Windows 10 Pro
Chrome 64-bit 72.0.3626.81

**Comment by drfish** [comment]
Incidentally I fired up Edge out of curiosity on the same machine and I'm _not_ getting this message.

**Comment by sakazuki** [comment]
Thank you for your report.

I confirmed the same error.
This error does not occur, when using Device storage.
It looks something around the storage module had been changed.

I will investigate this more

**Comment by alderg** [comment]
This is related to collaborative editing, it happens for files stored in OneDrive and Google Drive, but also for GitHub and Device files when using File, Synchronize. We see the following stack trace after files are saved:

TypeError: cell.getAttribute is not a function
    at ParallelState.toJSON (https://rawgit.com/sakazuki/step-functions-draw.io/master/aws-step-functions.js:850:22)
    at JSON.stringify (<anonymous>)
    at DrawioFileSync.objectToString
    at DrawioFileSync.fileSaved
    at DriveFile.DrawioFile.fileSaved
...

**Comment by sakazuki** [comment]
@alderg  Thank you for your information.
It is very helpful information. I think I could resolve these errors.

**Comment by alderg** [comment]
That said, custom data should really be stored in an XML node under cell.value, if that's an option at this point.

**Comment by sakazuki** [comment]
To use this fixed version, before jsdelvier cache refresh.
https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@d8f8ab0/aws-step-functions.js

**Comment by drfish** [comment]
I forgot to say this at the time, but thanks for the quick response and
fix! I am super impressed at how fast you got that solved.
