### ISSUE TITLE
Feature request: Possibility to set parameters field

### ISSUE THREAD

**Issue by parviainen-s** [sakazuki/step-functions-draw.io#17]
Tasks have an optional [parameters field](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html). This field is useful to be able to e.g. have a Task that writes to SNS (you specify the message in the parameters field).

Would it be possible to add a feature that allows us to set the parameters, even in the form of just some arbitrary JSON?

**Comment by sakazuki** [comment]
Hello @parviainen-s  
Thank you for your request.
I released v0.3.0 that support your request. please test it.
Regards

**Comment by parviainen-s** [comment]
I don't see a way to enter the parameters in the UI? There doesn't seem to be any "parameters" field in the settings of tasks.

**Comment by sakazuki** [comment]
Please update  plugin url. Use 0.3.0

**Comment by parviainen-s** [comment]
I did. Apparently the problem is that the parameters field is not added to existing nodes. So when I open an existing drawing created with an older version of the plugin, and try to add parameters to some existing task, I don't get the field. When I add a new task, I do. This means that I would have to re-create the entire drawing again using te new version of the plugin.

Probably there should be some "migration"  step which adds the parameters to existing tasks that don't ave it yet.
