### ISSUE TITLE
Resource URI checker is too strict

### ISSUE THREAD

**Issue by parviainen-s** [sakazuki/step-functions-draw.io#18]
The validator complains when using resource URIs such as _arn:aws:states:::sns:publish_.

[The official AWS documentation](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html#amazon-states-language-task-state-specifying-resource-arns) states that an acceptable resource is of the form _arn:partition:service:region:account:task_type:name_.

Thus, the regexp that checks the resource URI should be something like

`/^arn:[^:]+:(states|lambda):[^:]*:[^:]*:[^:]+:.+/`

**Comment by sakazuki** [comment]
Hello @parviainen-s  
Thank you for your request.
I released v0.3.0 that support your request. please test it.
Regards
