### ISSUE TITLE
Reloading template

### ISSUE THREAD

**Issue by zeuzere** [sakazuki/step-functions-draw.io#2]
Love the tool but ...

When you reload its not working, what ever format of file it is.
It lose all information after reloading the page 

if you put
    Start-> Task-> End  
save then reload page
if you export  StepFunctions-> Export JSON ,,,,  the JSON file is empty

thanks

**Comment by sakazuki** [comment]
Hello @zeuzere,

Thank you for your report.

What you report looks like the standard behavior of draw.io.
When you reload the page , All page data will be cleared.

Regards,

**Comment by zeuzere** [comment]
So... each time we use step-functions-draw we must over each time ?  Or:
1) Draw our graph
2) Export our JSON(for aws)
3) Export to XML (for draw.io)
Next time:
4) Import XML
5) Work on schema

And if by mistake we reload(f5) or what ever, we lose all the work... 
because the save does no work?....

is this correct ?
Thx

**Comment by sakazuki** [comment]
Hi,

Sorry, I cannot understand the case that you explain.
You should not reload  the page to avoid the lost of unsaved page.

Can you explain the steps to reproduce more detail and the information of browser ?

Regards,

**Comment by zeuzere** [comment]
![2018-06-01_20-04-08](https://user-images.githubusercontent.com/12201323/40868019-0a619f6e-65d7-11e8-9655-e6dab8beb789.gif)

1) I install graph on chart
2) you see all small icons below each graph
3) i insert data in task
4) i save and reload
5) like you see, small icons are not there anymore
6) data is there
7) only have the new graph data

**Comment by sakazuki** [comment]
Thank you for  your image.

I  understood it and confirm the behavior when I select Google Drive Storage.
When I select Browser Storage, It work well after reload.

I will see more details.

Regards,

**Comment by zeuzere** [comment]
Yes, it work in Device Storage,

I will probably use Device Storage since i will be able to put in our repository...

Again, 
Love the tool 
Easier to make any modification....
Just to move and connect task together, when you have a lot of Task, make this tool worth it....

Thanks, looking foward to see more dev

**Comment by seraphjiang** [comment]
Love this tool, but have same issue, will try device storage as workarround

**Comment by chrisware** [comment]
Same problem. Would love to be able to save to Google Drive. Workaround is to use device storage.

**Comment by logbon72** [comment]
Great tool! Thanks, using local storage as workaround for this also.

**Comment by sakazuki** [comment]
After my investigation, 
I guess that this cause is the Google Drive storage driver specification of draw.io
Though the Google Drive storage driver uses Google Realtime API(depreacted and shutdown on Jun, 2019), it does not support the plugin's codec.
cf: https://developers.google.com/realtime/deprecation

So, I arrive the conclusion that I cannot fix this issue.
Please use the other storage.

Regards,
