### ISSUE TITLE
Access to account without AWS AK/SK?

### ISSUE THREAD

**Issue by ANTGOMEZ** [sakazuki/step-functions-draw.io#20]
This is a really good tool for StepFunctions. However, what about the ability to set up AWSConfig with other type of access beyond Access/Secret Keys? 

We're not allowed to log in with keys anymore we use ADFS.

Thanks.

**Comment by sakazuki** [comment]
Hello @ANTGOMEZ .

Thank you for your question.
But I don't know the way to access AWS API without Access/Secret Keys.

It is possible to provide Access/Secret Keys in regardless of  using ADFS.
So I think it is better to request Access/Secret Keys to your AWS administrator.

Regards
