### ISSUE TITLE
Ability o t

### ISSUE THREAD

**Issue by fadams** [sakazuki/step-functions-draw.io#23]

**Comment by fadams** [comment]
Whilst it is possible to add comments in a number of places I've not been able to work out how to add a comment to the step function itself. I'd have assumed clicking the gear symbol on the Start object or possibly the StartAt transition, but neither of these seems possible.

Minor niggle I know, but it'd be nice to be able to generate everything possible in the JSON format.

**Comment by sakazuki** [comment]
Hi,

You can add a comment on a top level json with the following way.

![2019-06-24 07_32_06-test - draw io](https://user-images.githubusercontent.com/1878694/59982817-e4b40b00-9652-11e9-92be-5a2e22eb6fb1.png)


Does this solve your request ?

**Comment by fadams** [comment]
Ahh, Brilliant! That's spot on, thanks!

I can see it now re-reading the Quickstart on Github - totally missed it until you mentioned it. It'd be great if you could update the README.md to link in the picture you linked, it probably *should* be obvious, but I guess I've just proved however idiot proof there's always a bigger idiot .

Thanks for the reply, I appreciate it!

Cool plugin!

Cheers,

**Comment by sakazuki** [comment]
OK!
I updated README.md.
Thank you for your proposal.

Regards,
sakazuki
