### ISSUE TITLE
null JSONPath values get rendered as the string "null"

### ISSUE THREAD

**Issue by fadams** [sakazuki/step-functions-draw.io#24]
For things like InputPath, OutputPath, ResultPath etc. the JSON value null is valid and in ASL it means something different to the field being omitted.

In the UI if one selects say ResultPath and enters null the resulting JSON ASL gets rendered as
```
"ResultPath": "null"
```
as opposed to
```
"ResultPath": null
```
The value null is valid according to the ASL specification and has a specific meaning however I don't believe that the string "null" is valid JSONPath and certainly not a valid reference path.

**Comment by sakazuki** [comment]
Thank you for your report.
I fixed it, and released v0.3.1

Regards,
