### ISSUE TITLE
Blank screen on export

### ISSUE THREAD

**Issue by andybensongam** [sakazuki/step-functions-draw.io#3]
Hi
Thanks for providing this, its potentially amazing. But whenever I try and Export to JSON/YAML I get just a blank screen. Any ideas why please ?

I'm using v 9.1.8

Thanks

Andy

**Comment by sakazuki** [comment]
Hi Andy,
Could you explain more detail  the way to show blank screen ?

**Comment by andybensongam** [comment]
Hi

Thanks for getting back to me

I attach a document explaining

Regards

Andy

**Comment by sakazuki** [comment]
Hi Andy,

> I attach a document explaining

There is no attachment ...

**Comment by andybensongam** [comment]
[Uploading We created a step function diagram.doc…]()
[We created a step function diagram.docx](https://github.com/sakazuki/step-functions-draw.io/files/2455466/We.created.a.step.function.diagram.docx)

**Comment by andybensongam** [comment]
Added was saved as .doc github didnt support
