### ISSUE TITLE
Support for Dynamic Parallelism

### ISSUE THREAD

**Issue by gvasquez-waypoint** [sakazuki/step-functions-draw.io#30]
Can you please consider adding support for Map state type?

Ref: https://aws.amazon.com/blogs/aws/new-step-functions-support-for-dynamic-parallelism/

**Comment by sakazuki** [comment]
I will support Map state type. Maybe it is in a few days.

**Comment by sakazuki** [comment]
pre-release as 0.5.0-beta 
- https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.5.0-beta/dist/aws-step-functions.js

**Comment by sakazuki** [comment]
I released 0.5.0.
