### ISSUE TITLE
Export does not work

### ISSUE THREAD

**Issue by radiantone** [sakazuki/step-functions-draw.io#37]
aws-step-functions.js:1 Uncaught TypeError: p.awssf.expJSON is not a function
    at O (aws-step-functions.js:1)
    at Action.H [as funct] (aws-step-functions.js:1)
    at app.min.js:3263
    at mxPopupMenu.<anonymous> (app.min.js:376)
    at HTMLTableRowElement.<anonymous> (app.min.js:181)
﻿
​

**Comment by sakazuki** [comment]
Hi @radiantone 
I cannot reproduce the error in v0.6.1.
Please let me know more information to find the way to reproduce the error.

**Comment by radiantone** [comment]
Here is a screen shot. I went to draw.io and followed your steps to add the plugin.
![steperror](https://user-images.githubusercontent.com/25509097/74792080-57c95c00-528a-11ea-8dbe-91bac293c6ed.png)

**Comment by sakazuki** [comment]
I cannot reproduce the error yet.
Please let me show the flow's xml with [File]-[Export as]-[XML....]

**Comment by radiantone** [comment]
<mxGraphModel>
  <root>
    <object type="awssfRoot" name="" comment="" timeout_seconds="" version="" role_arn="" state_machine_arn="" id="0">
      <mxCell>
        <Object as="awssf" />
      </mxCell>
    </object>
    <mxCell id="1" parent="0" />
    <object label="StartAt" type="awssfStartAt" id="kxQ7RyInm61i6vWTneUj-13">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-1" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <pt as="awssf" />
      </mxCell>
    </object>
    <object label="Start" type="awssfStart" id="kxQ7RyInm61i6vWTneUj-1">
      <mxCell style="ellipse;whiteSpace=wrap;html=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
        <mxGeometry x="310" y="110" width="80" height="80" as="geometry" />
        <xt as="awssf" />
      </mxCell>
    </object>
    <object label="End" type="awssfEnd" id="kxQ7RyInm61i6vWTneUj-2">
      <mxCell style="ellipse;whiteSpace=wrap;html=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
        <mxGeometry x="310" y="490" width="80" height="80" as="geometry" />
        <St as="awssf" />
      </mxCell>
    </object>
    <object label="Next" type="awssfNext" id="kxQ7RyInm61i6vWTneUj-8">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-5" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <dt as="awssf" />
      </mxCell>
    </object>
    <object label="Catch" type="awssfCatch" placeholders="1" error_equals="" result_path="" weight="1" id="kxQ7RyInm61i6vWTneUj-11">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-10" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <mt as="awssf" />
      </mxCell>
    </object>
    <object label="Task" type="awssfTask" comment="" input_path="" output_path="" parameters="" result_path="" resource="" timeout_seconds="60" heartbeat_seconds="" id="kxQ7RyInm61i6vWTneUj-3">
      <mxCell style="shape=stencil(rZVNb4MwDIZ/DdcqkI2P48S6Y1Wph51TMCMqTVDC2m2/fiEBdUCyAavExa+xH78BjIdTWZIavAAxcgYPP3tBsBeQQ0EZ5EreC56BlEpWQWluCJEJryZMYhMSWUPWGO1CBCXHCkxGNoKf4ErzputAWQmCNm0Wbz30pO5pL5xmnDHVhHImB5kfedWMUKZq0YdphjaPBvPZxSaqFeEMDYiBerO508LLaow/D3NYihl66aF/YV4XYvx1mO3iQ0PBiIT8mazdUk8WWBLPhB2Ww/r3foWz5cc4gc13ZoPhVCmujw2nR5Kd3gR/Z7l1RJ0R7cfuem2tC2K0PojIJP3qpgw3kR+FcYSihzhIEuy7hnaMhtOCC/hl5oJWldlDroOvSbueJok+feYXuPmNLH5tbfvqSu1TV3XoLteWHYOp3X0/P4n/L0Oj8js70jWT56tV8/vSwjc=);whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="270" width="80" height="40" as="geometry" />
        <Et as="awssf" />
      </mxCell>
    </object>
    <object label="Succeed" type="awssfSucceed" comment="" input_path="" output_path="" id="kxQ7RyInm61i6vWTneUj-4">
      <mxCell style="shape=mxgraph.flowchart.terminator;html=1;whiteSpace=wrap;gradientColor=none;" parent="1" vertex="1">
        <mxGeometry x="530" y="250" width="80" height="40" as="geometry" />
        <Ct as="awssf" />
      </mxCell>
    </object>
    <object label="Next" type="awssfNext" id="kxQ7RyInm61i6vWTneUj-12">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-5" target="kxQ7RyInm61i6vWTneUj-2" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <dt as="awssf" />
      </mxCell>
    </object>
    <object label="Task2" type="awssfTask" comment="" input_path="" output_path="" parameters="" result_path="" resource="" timeout_seconds="60" heartbeat_seconds="" id="kxQ7RyInm61i6vWTneUj-5">
      <mxCell style="shape=stencil(rZVNb4MwDIZ/DdcqkI2P48S6Y1Wph51TMCMqTVDC2m2/fiEBdUCyAavExa+xH78BjIdTWZIavAAxcgYPP3tBsBeQQ0EZ5EreC56BlEpWQWluCJEJryZMYhMSWUPWGO1CBCXHCkxGNoKf4ErzputAWQmCNm0Wbz30pO5pL5xmnDHVhHImB5kfedWMUKZq0YdphjaPBvPZxSaqFeEMDYiBerO508LLaow/D3NYihl66aF/YV4XYvx1mO3iQ0PBiIT8mazdUk8WWBLPhB2Ww/r3foWz5cc4gc13ZoPhVCmujw2nR5Kd3gR/Z7l1RJ0R7cfuem2tC2K0PojIJP3qpgw3kR+FcYSihzhIEuy7hnaMhtOCC/hl5oJWldlDroOvSbueJok+feYXuPmNLH5tbfvqSu1TV3XoLteWHYOp3X0/P4n/L0Oj8js70jWT56tV8/vSwjc=);whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="380" width="80" height="40" as="geometry" />
        <Et as="awssf" />
      </mxCell>
    </object>
    <object label="Retry" type="awssfRetry" placeholders="1" error_equals="States.ALL" interval_seconds="" max_attempts="3" backoff_rate="2" weight="1" id="kxQ7RyInm61i6vWTneUj-6">
      <mxCell style="edgeStyle=orthogonalEdgeStyle;curved=1;html=1;exitX=0.5;exitY=1;entryX=1;entryY=0.5;startArrow=none;startFill=0;jettySize=auto;orthogonalLoop=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint y="60" as="sourcePoint" />
          <mxPoint x="60" as="targetPoint" />
        </mxGeometry>
        <ht as="awssf" />
      </mxCell>
    </object>
    <object label="Retry" type="awssfRetry" placeholders="1" error_equals="" interval_seconds="" max_attempts="3" backoff_rate="2" weight="1" id="kxQ7RyInm61i6vWTneUj-7">
      <mxCell style="edgeStyle=orthogonalEdgeStyle;curved=1;html=1;exitX=0.5;exitY=1;startArrow=none;startFill=0;jettySize=auto;orthogonalLoop=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="350" y="300" as="targetPoint" />
        </mxGeometry>
        <ht as="awssf" />
      </mxCell>
    </object>
    <object label="Wait" type="awssfWait" comment="" input_path="" output_path="" seconds="" id="kxQ7RyInm61i6vWTneUj-9">
      <mxCell style="shape=mxgraph.flowchart.delay;whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="590" width="80" height="40" as="geometry" />
        <Tt as="awssf" />
      </mxCell>
    </object>
    <object label="Fail" type="awssfFail" comment="" error="" cause="" id="kxQ7RyInm61i6vWTneUj-10">
      <mxCell style="shape=mxgraph.flowchart.terminator;html=1;whiteSpace=wrap;gradientColor=none;" parent="1" vertex="1">
        <mxGeometry x="530" y="380" width="80" height="40" as="geometry" />
        <bt as="awssf" />
      </mxCell>
    </object>
  </root>
</mxGraphModel>

**Comment by radiantone** [comment]
`<mxGraphModel>
  <root>
    <object type="awssfRoot" name="" comment="" timeout_seconds="" version="" role_arn="" state_machine_arn="" id="0">
      <mxCell>
        <Object as="awssf" />
      </mxCell>
    </object>
    <mxCell id="1" parent="0" />
    <object label="StartAt" type="awssfStartAt" id="kxQ7RyInm61i6vWTneUj-13">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-1" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <pt as="awssf" />
      </mxCell>
    </object>
    <object label="Start" type="awssfStart" id="kxQ7RyInm61i6vWTneUj-1">
      <mxCell style="ellipse;whiteSpace=wrap;html=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
        <mxGeometry x="310" y="110" width="80" height="80" as="geometry" />
        <xt as="awssf" />
      </mxCell>
    </object>
    <object label="End" type="awssfEnd" id="kxQ7RyInm61i6vWTneUj-2">
      <mxCell style="ellipse;whiteSpace=wrap;html=1;fillColor=#ffe6cc;strokeColor=#d79b00;" parent="1" vertex="1">
        <mxGeometry x="310" y="490" width="80" height="80" as="geometry" />
        <St as="awssf" />
      </mxCell>
    </object>
    <object label="Next" type="awssfNext" id="kxQ7RyInm61i6vWTneUj-8">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-5" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <dt as="awssf" />
      </mxCell>
    </object>
    <object label="Catch" type="awssfCatch" placeholders="1" error_equals="" result_path="" weight="1" id="kxQ7RyInm61i6vWTneUj-11">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-10" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <mt as="awssf" />
      </mxCell>
    </object>
    <object label="Task" type="awssfTask" comment="" input_path="" output_path="" parameters="" result_path="" resource="" timeout_seconds="60" heartbeat_seconds="" id="kxQ7RyInm61i6vWTneUj-3">
      <mxCell style="shape=stencil(rZVNb4MwDIZ/DdcqkI2P48S6Y1Wph51TMCMqTVDC2m2/fiEBdUCyAavExa+xH78BjIdTWZIavAAxcgYPP3tBsBeQQ0EZ5EreC56BlEpWQWluCJEJryZMYhMSWUPWGO1CBCXHCkxGNoKf4ErzputAWQmCNm0Wbz30pO5pL5xmnDHVhHImB5kfedWMUKZq0YdphjaPBvPZxSaqFeEMDYiBerO508LLaow/D3NYihl66aF/YV4XYvx1mO3iQ0PBiIT8mazdUk8WWBLPhB2Ww/r3foWz5cc4gc13ZoPhVCmujw2nR5Kd3gR/Z7l1RJ0R7cfuem2tC2K0PojIJP3qpgw3kR+FcYSihzhIEuy7hnaMhtOCC/hl5oJWldlDroOvSbueJok+feYXuPmNLH5tbfvqSu1TV3XoLteWHYOp3X0/P4n/L0Oj8js70jWT56tV8/vSwjc=);whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="270" width="80" height="40" as="geometry" />
        <Et as="awssf" />
      </mxCell>
    </object>
    <object label="Succeed" type="awssfSucceed" comment="" input_path="" output_path="" id="kxQ7RyInm61i6vWTneUj-4">
      <mxCell style="shape=mxgraph.flowchart.terminator;html=1;whiteSpace=wrap;gradientColor=none;" parent="1" vertex="1">
        <mxGeometry x="530" y="250" width="80" height="40" as="geometry" />
        <Ct as="awssf" />
      </mxCell>
    </object>
    <object label="Next" type="awssfNext" id="kxQ7RyInm61i6vWTneUj-12">
      <mxCell style="endArrow=classic;html=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-5" target="kxQ7RyInm61i6vWTneUj-2" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="60" y="60" as="targetPoint" />
        </mxGeometry>
        <dt as="awssf" />
      </mxCell>
    </object>
    <object label="Task2" type="awssfTask" comment="" input_path="" output_path="" parameters="" result_path="" resource="" timeout_seconds="60" heartbeat_seconds="" id="kxQ7RyInm61i6vWTneUj-5">
      <mxCell style="shape=stencil(rZVNb4MwDIZ/DdcqkI2P48S6Y1Wph51TMCMqTVDC2m2/fiEBdUCyAavExa+xH78BjIdTWZIavAAxcgYPP3tBsBeQQ0EZ5EreC56BlEpWQWluCJEJryZMYhMSWUPWGO1CBCXHCkxGNoKf4ErzputAWQmCNm0Wbz30pO5pL5xmnDHVhHImB5kfedWMUKZq0YdphjaPBvPZxSaqFeEMDYiBerO508LLaow/D3NYihl66aF/YV4XYvx1mO3iQ0PBiIT8mazdUk8WWBLPhB2Ww/r3foWz5cc4gc13ZoPhVCmujw2nR5Kd3gR/Z7l1RJ0R7cfuem2tC2K0PojIJP3qpgw3kR+FcYSihzhIEuy7hnaMhtOCC/hl5oJWldlDroOvSbueJok+feYXuPmNLH5tbfvqSu1TV3XoLteWHYOp3X0/P4n/L0Oj8js70jWT56tV8/vSwjc=);whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="380" width="80" height="40" as="geometry" />
        <Et as="awssf" />
      </mxCell>
    </object>
    <object label="Retry" type="awssfRetry" placeholders="1" error_equals="States.ALL" interval_seconds="" max_attempts="3" backoff_rate="2" weight="1" id="kxQ7RyInm61i6vWTneUj-6">
      <mxCell style="edgeStyle=orthogonalEdgeStyle;curved=1;html=1;exitX=0.5;exitY=1;entryX=1;entryY=0.5;startArrow=none;startFill=0;jettySize=auto;orthogonalLoop=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint y="60" as="sourcePoint" />
          <mxPoint x="60" as="targetPoint" />
        </mxGeometry>
        <ht as="awssf" />
      </mxCell>
    </object>
    <object label="Retry" type="awssfRetry" placeholders="1" error_equals="" interval_seconds="" max_attempts="3" backoff_rate="2" weight="1" id="kxQ7RyInm61i6vWTneUj-7">
      <mxCell style="edgeStyle=orthogonalEdgeStyle;curved=1;html=1;exitX=0.5;exitY=1;startArrow=none;startFill=0;jettySize=auto;orthogonalLoop=1;strokeColor=#000000;strokeWidth=1;fontSize=12;" parent="1" source="kxQ7RyInm61i6vWTneUj-3" target="kxQ7RyInm61i6vWTneUj-3" edge="1">
        <mxGeometry width="60" height="60" relative="1" as="geometry">
          <mxPoint as="sourcePoint" />
          <mxPoint x="350" y="300" as="targetPoint" />
        </mxGeometry>
        <ht as="awssf" />
      </mxCell>
    </object>
    <object label="Wait" type="awssfWait" comment="" input_path="" output_path="" seconds="" id="kxQ7RyInm61i6vWTneUj-9">
      <mxCell style="shape=mxgraph.flowchart.delay;whiteSpace=wrap;gradientColor=none;html=1;" parent="1" vertex="1">
        <mxGeometry x="310" y="590" width="80" height="40" as="geometry" />
        <Tt as="awssf" />
      </mxCell>
    </object>
    <object label="Fail" type="awssfFail" comment="" error="" cause="" id="kxQ7RyInm61i6vWTneUj-10">
      <mxCell style="shape=mxgraph.flowchart.terminator;html=1;whiteSpace=wrap;gradientColor=none;" parent="1" vertex="1">
        <mxGeometry x="530" y="380" width="80" height="40" as="geometry" />
        <bt as="awssf" />
      </mxCell>
    </object>
  </root>
</mxGraphModel>

`

**Comment by radiantone** [comment]
I can't upload the XML. Is there another way to share it?

**Comment by sakazuki** [comment]
I found this error occurs in the case #38 also. Maybe the cause is same .  I investigate it.

**Comment by sakazuki** [comment]
Please read 
https://github.com/sakazuki/step-functions-draw.io/issues/38#issuecomment-589397932
