### ISSUE TITLE
Action icons disappear when loading saved file

### ISSUE THREAD

**Issue by jwarhurst** [sakazuki/step-functions-draw.io#38]
I've noticed the little buttons for each shape (i.e. next/catch/retry/config) are not coming back after you load a saved file. I've tried using browser and device storage, with Chrome and Firefox. Are they intended to come back?

**Comment by sakazuki** [comment]
Hi, I confirmed the reported behavior. I will investigate the cause.

**Comment by sakazuki** [comment]
I released v0.6.2. Please try it.

v0.6.0 and v0.6.1 saved data was corrupted. 
v0.6.0 and v0.6.1 cannot load correctly data that was saved with other version.

**Comment by jwarhurst** [comment]
Working as expected now. Thank you so much!
