### ISSUE TITLE
Does not seem to work in drawio-desktop

### ISSUE THREAD

**Issue by cloudtagger** [sakazuki/step-functions-draw.io#43]
Hello,
This doesn't seem to work on the [desktop version](https://github.com/jgraph/drawio-desktop). Maybe I am doing something wrong.

**Comment by cloudtagger** [comment]
Actually now its not working on the browser either. I get this error from console.

> (index):1 Refused to load the script 'https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.6.2/dist/aws-step-functions.js' because it violates the following Content Security Policy directive: "script-src 'self' https://storage.googleapis.com https://apis.google.com https://*.pusher.com https://code.jquery.com https://www.dropbox.com https://api.trello.com 'sha256-JqdgAC+ydIDMtmQclZEqgbw94J4IeABIfXAxwEJGDJs=' 'sha256-4Dg3/NrB8tLC7TUSCbrtUDWD/J6bSLka01GHn+qtNZ0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by sakazuki** [comment]
Hi
This is the specification of fesktop.
see detail https://github.com/jgraph/drawio-desktop/issues/276#issuecomment-634942885

**Comment by sakazuki** [comment]
Workaround is the following.

1. Save **[aws-step-functions.js](https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.6.2/dist/aws-step-functions.js)** on your local disk (ex. **c:/Users/user1/Downloads/aws-step-functions.js**)
2. On drawio desktop, click  [Extras] -[ Plugins... ]- [Add], And Input **c:/Users/user1/Downloads/aws-step-functions.js**
