### ISSUE TITLE
Pass state should not have Resource attribute

### ISSUE THREAD

**Issue by c10h22** [sakazuki/step-functions-draw.io#5]
Hi,

When generating a workflow with Pass state, we get `Resource: !<tag:yaml.org,2002:js/undefined> ` as an attribute which comes from these lines:

https://github.com/sakazuki/step-functions-draw.io/blob/928994827eaa0949e17ba0d3589e514aa72f513b/aws-step-functions.js#L374-L380

This could be fixed by just removing Resource attribute

**Comment by sakazuki** [comment]
@c10h22  Thanks for your comment. I fixed it.
