### ISSUE TITLE
app.diagrams.io plugin is not loading

### ISSUE THREAD

**Issue by skroidslab** [sakazuki/step-functions-draw.io#51]
I guess with the recent updates to the browser security policies, the JS is finiding it hard to load in app.diagrams.io (earlier draw.io). Can this be iinvestigated? The errors are below (as seen on the browser developer tools console) -

(index):185 A parser-blocking, cross site (i.e. different eTLD+1) script, https://js.pusher.com/4.3/pusher.min.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
mxscript @ (index):185
(index):185 A parser-blocking, cross site (i.e. different eTLD+1) script, https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.6.3/dist/aws-step-functions.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
mxscript @ (index):185
(index):1 Refused to load the script 'https://cdn.jsdelivr.net/gh/sakazuki/step-functions-draw.io@0.6.3/dist/aws-step-functions.js' because it violates the following Content Security Policy directive: "script-src https://www.dropbox.com https://api.trello.com 'self' https://storage.googleapis.com https://apis.google.com https://*.pusher.com https://code.jquery.com 'sha256-JqdgAC+ydIDMtmQclZEqgbw94J4IeABIfXAxwEJGDJs=' 'sha256-4Dg3/NrB8tLC7TUSCbrtUDWD/J6bSLka01GHn+qtNZ0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by sakazuki** [comment]
Please see this comment.
https://github.com/sakazuki/step-functions-draw.io/issues/44#issuecomment-668818202
